### ISSUE TITLE
Missing Wildlife ManhunterOnTameChance?

### ISSUE THREAD

**Issue by CodeOptimist** [Mehni/kNumbers#15]
I accidentally removed some columns from the Wildlife tab, and I can't seem to find what I presume is _ManhunterOnTameChance_? I don't know if that's the actual name. I found _ManhunterOnDamageChance_ and every other column, but not _OnTame_.

It's the column with both a wolf and hand icon superimposed, to the right of the wolf (...OnTame), which I can't seem to find in the menus.

Did I miss it somewhere?

(Thank you for your work, awesome improvements!)

**Comment by CodeOptimist** [comment]
Never mind, it reappeared with a full game restart!

**Comment by Mehni** [comment]
> (Not under "Misc", but rather the column reappeared.)

Still a bug. Thanks for reporting.
