### ISSUE TITLE
[Sugestion] Right click for more options

### ISSUE THREAD

**Issue by YPetremann** [Mehni/kNumbers#17]
As for now Right-click is for column deletion, I see that it allow too easy missclick and that there is no place for more option.
Instead I this it should provide a context menu with the options to:
- remove the column
- toggle the column header style (horizontal text, vertical text, icon or hidden) depending of availlable style for the column
- set the style of the column :
  - Current Job (icon, text)
  - Ability (likeness icon or not) (level bar, numeric level)
  - Chirugical operation (big button, compact icon)
  - ...

**Comment by Mehni** [comment]
Column headers have only one style, support for multiple styles is non easy. I'd need an icon for each work type (including modded) and a bunch of other icons that I certainly can't capture in an image. Vertical alignment, as Fluffy shows, is pretty difficult to get right with resolution scaling.

That leaves the core of your issue; it's too easy to misclick. I can agree with that. Maybe an extra (optional) modifier key is warranted. I'll need to look at the transpiler again to see how easy that is. Different functionality for control click, maybe.

**Comment by Mehni** [comment]
Closing this. Too much complexity for the gain.
