### ISSUE TITLE
[Bug] all works are removed when removing one

### ISSUE THREAD

**Issue by YPetremann** [Mehni/kNumbers#18]
Actually when removing one work, it remove all of them in the current view.

**Comment by Mehni** [comment]
Incompatibility with Worktab. To solve this (and a related issue) I would need a better way of detecting what column the mouse is over. Thusfar I have not found it.

**Comment by CodeOptimist** [comment]
Dang, when there's a Skill column and Fluffy's Work Tab is enabled, right clicking removes the wrong column (an adjacent one instead) as well. Sounds like the same bug. That sounds tricky. Thanks for the wonderful mods Mehni.
