### ISSUE TITLE
Error log for v2.0.1.0.4 build

### ISSUE THREAD

**Issue by AndShy** [Mehni/kNumbers#19]
just errors. idk what it affect for, but hugslib show debug log
starts from 1395 line 
https://gist.github.com/HugsLibRecordKeeper/26a175e3b3a557a0d6ace2d1a935a9f7

**Comment by Mehni** [comment]
Update your copy of WorkTab. Numbers needs at least version 3.8.281 which was released 21 Nov 2018. You are on 3.4.185 from 30 Oct 2018.

Get the latest from https://github.com/FluffierThanThou/WorkTab/releases/latest or Steam.
