### ISSUE TITLE
Is FindMostSevereHediff Backwards?

### ISSUE THREAD

**Issue by maarxx** [Mehni/kNumbers#21]
https://github.com/Mehni/kNumbers/blob/fc9320b45bc0a8c41b2f2c67f68107fb89e84848/Numbers/PawnColumnWorkers/PawnColumnWorker_DiseaseProgression.cs#L167

Hey, is this backwards?

Looks like you're trying to find the most severe hediff, which I'm guessing is the most life-threatening hediff.

But looks like you're trying to find the one with the largest delta, where the largest delta would be the hediff with the most immunity and the least severity.

Looks backwards to me at first glance, but haven't tested it.

**Comment by Mehni** [comment]
Hey maarxx, good to hear from you! Thanks for taking an interest :)

This column tries to find the pawn with the largest delta. The reasoning behind showing a delta is that 30% immunity and 60% severity is cause for concern. 60% Severity by itself isn't a cause, but combined with that low immunity it is. 90% Severity and 92% immunity on the other hand isn't something a player would be worried about.

You're probably right that the calculation is backwards somewhere. I think that's handled by colours, but I'll have to check in-game.

**Comment by Mehni** [comment]
Edit by way of double post:

It's definitely named poorly, that's for sure. FindMostThreatening is a better fit for the contents and intent.
