### ISSUE TITLE
[Feature Request] Leather Type in animals tab

### ISSUE THREAD

**Issue by kaedys** [Mehni/kNumbers#31]
The animals tab shows both meat amount and leather amount, which is awesome, but there doesn't appear to be a way to add leather _type_ to the table.  It'd be really handy to be able to sort by the type of leather that drops, especially when playing with multiple mods that add additional leathers (ex. Alpha Animals, Magical Menagerie, etc.)

**Comment by Mehni** [comment]
Done. Thanks for the suggestion.
