### ISSUE TITLE
Requested display elements (and some miscellaneous other stuff)

### ISSUE THREAD

**Issue by kaedys** [Mehni/kNumbers#36]
Here are some display elements, broken down by the top-level category (colonists, animals, enemies, etc), that I feel are missing and/or have desired to have displayed:

**Colonists**
* Info `i` icon, for opening that pawn's stat page directly.
* Beauty (this is weirdly present as an option for _corpses_, but not for colonists =P)
* Hunger Rate - AA Mimes... >.>
* Neural Heat Recovery Rate
* Toxic Sensitivity
* Rest Fall Rate - this actually isn't even displayed in the vanilla pawn status window, but it's useful, especially with Royalty implants that can affect it
* Incoming Damage Multiplier (certain mods add items or implants that affect this).
* `isBad` Hediffs - the existing hediff display becomes largely useless once you start bionically-augmenting many of your colonists, as it shows up equally for beneficial hediffs as it does for bad ones.  Just displaying hediffs marked as `isBad` would be helpful for identifying pawns with illnesses, scars, ailments, missing limbs, etc. 
* Maybe also exclude addictions from the above `isBad` Hediff element as well, and have a separate display element for them specifically.  Notably, displaying "chemical need" shows up with a half-filled bar even for colonists with no addictions, so you can't really use that to filter on addictions.
* [_Stretch Goal_] If Simple Sidearms is displayed, an additional element displaying the all of the weapons, including sidearms, that the pawn has equipped or is carrying.  Not sure if this is possible, but it would be immensely helpful when managing weapon setups across a colony.

**Enemies**
* Info `i` icon, for opening that pawn's stat page directly.
* The same `isBad` Hediffs ask above, for filtering out "damaged goods" in incoming raids when evaluating who you want to, um, "acquire".  Same with the addictions one.
* Focus type.  This is an option for colonists, but not incoming raiders.  Important if your primary method of gaining psycasters is via Anima Tree worship.

**Animals**
* Info `i` icon, for opening that pawn's stat page directly.
* The same `isBad` Hediffs ask above, and the addictions ones.  Especially with A Dog Said, this is useful for identifying animals that are good targets for bionic replacement parts.  In addition, Pregnancy shows up as a hediff, so it becomes pretty difficult pretty quickly to identify animals that need extra parts, scar removal, etc.
* Hunger Rate - Useful for evaluating which animals are too expensive to keep around.
* Body Size (which is also equal to Maximum Food, I believe).  Certain things are restricted by body size, and since it impacts maximum food, it can be handy for evaluating which animals to keep, or bring on a caravan.
* Intelligence/Trainability.
* Age in Days, and also Mature Age.  Or alternatively, a "% Adult" (Age / Mature Age) and/or "Days until Adult" (Mature Age - Age)
* Nuzzle Interval
* Life expectancy
* Age as a percentage of life expectancy
* Years before life expectancy

**Wild Animals**
* The same `isBad` Hediffs ask above, and _maybe_ the addictions ones (hopefully not too many wild animals getting into your beer supply...).  Good for filtering out animals with scars or ailments like Asthma.
* Hunger Rate
* Body Size
* Meat Type
* Life expectancy
* Age as a percentage of life expectancy
* Years before life expectancy

**Miscellaneous/Bugs**
* For Wild Animals, the table cannot be sorted by Manhunter On Damaged chance, and the header for that column also lacks a tooltip.
* If a column is added to a pane more than once (usually by accident), right-clicking the column header to remove that duplicate column removes all copies of that column from the table.  This is a bit annoying, as if you accidentally duplicate a column, removing it removes the one you actually want, which you then have to add back in and move back to it's proper position.
* The Records and Misc lists are not sorted (or if they are, I can't divine how).  It'd be nice if these two elements were sorted alphabetically.

**Comment by Mehni** [comment]
That's quite the list. I'll go through them one by one.


- `i`nfo button
Numbers is meant to replace that horrid menu. No.
- Beauty
Nope. Corpses have beauty because they are ugly to look at and pawns go sad. Kimmy, no matter how pretty she is, does not have a real beauty stat.
- Hunger Rate 
- Neural Heat Recovery Rate
- Toxic Sensitivity
- Rest Fall Rate
These are all "maybe". I wouldn't be surprised if some of 'm are already present, but a lot of these stats are tedious to implement: there are no pawn column defs for them.
- Incoming Damage Multiplier
I'll take a look. Looks like this was added as a proper stat (instead of the ugly way Tough worked) so might be doable.
- `isBad` Hediffs
Oft requested, need to do this.
- SimpleSidearms
Nope. Not going to bother. 
- Focus on raiders
Sure.
- Animals bodysize/intelligence/trainability
bodysize is tedious. Intelligence/Trainability is a maybe. Seems useful
- Age and age related stuff
Seems very niche, and also very much overlapping with one another. If I were to do this, it would be one column with a neat graphic which relays all of that. Sounds like too much effort.
-  sorting Manhunter On Damaged chance
Blame Tynan.
- Removing duplicate
Yeah, known issue. Can't think of a good way to fix yet
- Sorting Records and Misc
iirc Records is sorted the same way the game keeps 'm. Not changing that.
Misc is sorted by -- hahaha no it's not sorted at all.

**Comment by kaedys** [comment]
> * `i`nfo button
Numbers is meant to replace that horrid menu. No.

But Numbers doesn't display everything, and that info page has additional tabs, like health and permits and such that Numbers doesn't address.  The stat pane also often has calculation steps for various stats.  It's _very_ common, for example, for me to be looking through my pawns various stats in Numbers and go "wait, why does X have such a high GeneralLaborSpeed?" or "Woah, why's X's medical tend stat so bad?".  Having quick access to the `i` icon to be able to access those would be super handy.

> * Beauty
Nope. Corpses have beauty because they are ugly to look at and pawns go sad. Kimmy, no matter how pretty she is, does not have a real beauty stat.

Except...they do?  Pawns _do_ have a beauty stat, and it affects their social interactions.  That's the entire basis behind traits like Ugly, Pretty, etc, and behind things like the Asthetic Shaper.  I'm not talking beauty as in the stat that impacts the Beauty environmental need, I'm talking about the _social stat_.  It's just a straight integer, last I checked, usually ranging between -2 and +2 (default 0, of course).

**Comment by Mehni** [comment]
So you need the trait then, that's different. And maybe see if they are misformed or w/e the social opinion thing is. 

Yeah, I oughta do the traits list. There's a submod doing it, but I can do it better. The misformed bit, well, if I do `isBad` hediffs, then that'll be covered by that.

**Comment by kaedys** [comment]
It's not just the traits, though, because hediffs can affect it (Asthetic Shaper and Asthetic Nose, plus some modded ones).  It's a sum of those, so an Ugly pawn with an Asthetic Nose is back to beauty 0, same as default.  And since the "base" social reaction to a pawn is 20x their beauty stat, it can have a pretty considerable impact on interactions and how often that pawn gets in social fights and such.

**Comment by angelolocritani** [comment]
>For Wild Animals, the table cannot be sorted by Manhunter On Damaged chance, and the header for that column also lacks a tooltip.

it seems that in last version you _can_ sort based on that column and there's a tooltip too
![immagine](https://user-images.githubusercontent.com/67960642/129097435-1c3c093a-2b31-43c7-b1da-2d338b380048.png)

**Comment by Mehni** [comment]
Feel free to reopen if there are things still missing.
