### ISSUE TITLE
Ideology column is gone

### ISSUE THREAD

**Issue by nixxquality** [Mehni/kNumbers#41]
Before the update 3 days ago there used to be a column in Misc called "Ideo" that could be used to spot Ideologies of pawns on the map.

Looking at the changes since then my best guess is that this is what caused it to disappear:
[diff 1](https://github.com/Mehni/kNumbers/compare/Mehni:267319baa188dd14d64fdd24b14e2c494306e76e...master#diff-0b1c9e82e60380f26f8880921f1ed5ce8334d64530fd073eaf03c2cc2fd8e1d0R254-R255)

I'm not familiar with the code, but I'm guessing that this is where you get Misc stats from and forcing no ideology made it stop appearing.

The only reference to Ideology I can find is in the prisoner code: [diff 2](https://github.com/Mehni/kNumbers/compare/Mehni:267319baa188dd14d64fdd24b14e2c494306e76e...master#diff-274466a20ff49e6bc3c770e2de531f69cbc5a37858f5eb2940af9562f4dc4055R59)

Would it be possible for you to add an Ideology column?

**Comment by Mehni** [comment]
It never had an ideology column.

Feel free to submit a PR. I don't have ideology myself so hard to develop and test.

**Comment by nixxquality** [comment]
I don't own the game either.

**Comment by ravenx99** [comment]
I can add an Ideology column, but it has no header so I can't sort on it or remove the column.  I'm suspecting this is why.

@Mehni I (RavenX) sent you a friend request on Steam.  Add me and I'll gift you Ideology.  Numbers is awesome and makes my pawns' lives so much easier.
