### ISSUE TITLE
Numbers tab throws error with CE

### ISSUE THREAD

**Issue by 321nick** [Mehni/kNumbers#43]
The number tab throws an error and doesnt open when trying to open it with CE installed

Log: [https://gist.github.com/b4e91c215a80f2009a2fbd1580d3a885](https://steamcommunity.com/linkfilter/?url=https://gist.github.com/b4e91c215a80f2009a2fbd1580d3a885)

**Comment by Mehni** [comment]
If this is still a thing: blame CE =)
