### ISSUE TITLE
If the ideology column is displayed the mod breaks when the colony has a baby

### ISSUE THREAD

**Issue by DrStalker** [Mehni/kNumbers#47]
![Screenshot](https://user-images.githubusercontent.com/1460252/198214703-706136cd-c633-434e-8a92-33aca51734f7.png)

You can see it gives up right when it reaches Parsons' ideology. I assume this is because the baby has no ideology, and the mod was written with the (safe before version 1.4) assumption a pawn will always have an ideology.

None of the mod buttons respond at all, meaning the column cannot be removed.   To work around this I edited my save game files and deleted Numbers_Ideology from the saved game data:

```
				<li Class="Numbers.WorldComponent_Numbers">
					<Numbers_Numbers_MainTable>
						...
						<li>Numbers_Ideology</li>
						...
					</Numbers_Numbers_MainTable>
				</li>
```

This is a nicer fix than my second plan of murdering the baby, who is less valuable to me than a functional Numbers mod.

**Comment by Mehni** [comment]
I love this bug report, thank you for the laugh.

I'll get right on that.

**Comment by Mehni** [comment]
Fixed.
