### ISSUE TITLE
Bug: Sorting by skill seems to discount skills gained/lost by genes

### ISSUE THREAD

**Issue by dhruvit-r** [Mehni/kNumbers#65]
So, it seems that sorting pawns by skill discounts the skills gained by the pawn due to genes. Attaching a video to show the issue.

https://user-images.githubusercontent.com/5932865/226552151-20bedaf5-1ad2-44b3-b83e-7072891bef0d.mp4

**Comment by Mehni** [comment]
I'm fairly sure this was fixed by commit 9e2ac68
