### ISSUE TITLE
Missing Stat Request

### ISSUE THREAD

**Issue by YReid** [Mehni/kNumbers#74]
Misc Stat Will Remaining for prisoners

**Comment by Mehni** [comment]
I know it's a stat, I know it exists, I've seen it with my own eyes. I legit couldn't find it in the dang RimWorld code for the 10 minutes I spent looking.

he;lp

**Comment by nebuchadnezzer2** [comment]
Speaking of missing stats, I was looking for, and failed to find, Food Consumption in Numbers as well, and found _that_ in RimWorld\Data\Core\Languages\English\Keyed\ITabs.xml, as FoodConsumption.
Just found WillLevel in the same file for Ideology (RimWorld\Data\Core\Languages\English\Keyed\ITabs.xml).

Maybe that helps? Was just after Food Consumption for an easy side-by-side comparison of my pawns 😂

**Comment by Mehni** [comment]
Thank you! That was the exact hint I needed to implement it.
