### ISSUE TITLE
Sorting isn't remembered in the animal/wildlife tabs when you reopen them

### ISSUE THREAD

**Issue by marouamghar** [Mehni/kNumbers#79]
In contrary to the numbers tab where it remembers the sorting used, it seems whenever you close and reopen that tab, it sorts them alphabetically again. Saving it in a preset and loading it again doesn't seem to solve it.

**Comment by marouamghar** [comment]
Addition: when using the animals/wildlife filter in the numbers tab, the sorting is conserved in that tab (but not in the 2 others, ofc)

**Comment by Mehni** [comment]
Dupe #20
